services:
  go-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: "go-test"
    command: [ "go", "test", "-v", "./test-cases/..." ]
    environment:
      - DB_HOST=go-test-db:5432
      - DB_USER_FILE=/run/secrets/go-test-db-user
      - DB_PASSWORD_FILE=/run/secrets/go-test-db-password
    depends_on:
      - go-test-db
    networks:
      - test
    secrets:
      - go-test-db-user
      - go-test-db-password

  go-test-dlv:
    build:
      context: .
      dockerfile: Dockerfile
      target: "go-test-dlv"
    image: go-test-dlv
    command: [ "dlv", "test", "--listen=:40000", "--headless=true", "--api-version=2", "--accept-multiclient", "./test-cases/created-at", "--", "-test.v", "-test.run", "^TestCreatedAtRepository_Create_WithADuplicatePrimaryKeyFails" ]
    environment:
      - DB_HOST=go-test-db:5432
      - DB_USER_FILE=/run/secrets/go-test-db-user
      - DB_PASSWORD_FILE=/run/secrets/go-test-db-password
    expose:
      - 40000
    ports:
      - "127.0.0.1:40000:40000"
    depends_on:
      - go-test-db
    networks:
      - test
    secrets:
      - go-test-db-user
      - go-test-db-password

  go-test-db:
    image: postgres:16-alpine
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER_FILE=/run/secrets/go-test-db-user
      - POSTGRES_PASSWORD_FILE=/run/secrets/go-test-db-password
    expose:
      - 5432
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - test
    secrets:
      - go-test-db-user
      - go-test-db-password
    user: ${DOCKER_USER}
    volumes:
      - ./data/go-test-db/data:/var/lib/postgresql/data

  lint:
    image: golangci/golangci-lint:v2.3.0
    entrypoint: [ "golangci-lint" ]
    command: [ "run" ]
    environment:
      - GOCACHE=/.cache/go-build
      - GOMODCACHE=/.cache/mod
      - GOLANGCI_LINT_CACHE=/.cache/golangci-lint
    user: ${DOCKER_USER}
    working_dir: "/app"
    volumes:
      - ./:/app
      - ${GOCACHE}:/.cache/go-build
      - ${GOMODCACHE}:/.cache/mod
      - ${GOLANGCI_LINT_CACHE}:/.cache/golangci-lint

networks:
  test:
    name: protoc-gen-crud_test

secrets:
  go-test-db-user:
    file: docker/go-test-db/secrets/user
  go-test-db-password:
    file: docker/go-test-db/secrets/password
